version: '2'
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    restart: unless-stopped
    ports:
      - "8282:8282"
    volumes:
      - ./config:/usr/src/app/config
